Management/urls.py
from django.urls import path
from . import views


app_name = "Management"
urlpatterns=[
    #path("", views.index, name="Home"),
    path('', views.indexLogin, name= 'indexLogin'),
    path('temp/', views.update_employee_salaries, name='update'),
    path('login/', views.login_view, name='login_view'),
    path('register/', views.register, name='register'),
    # path('adminpage/', views.admin, name='adminpage'),
    path('index/', views.index, name='hr'),
    path('indexEMP/', views.indexEMP, name='employee'),

    path("fav/", views.view_fav, name="View_Favourite"),
    path("addfav/", views.add_fav, name="Add_Favourite"),
    path("addcompl/", views.add_complaint, name="Add_Complaint"),
    path("compl/", views.view_complaint, name="View_Complaint"),
    path("searchEMP/", views.searchemp, name="searchEMP"),
    path("signup/", views.sign_up, name="Sign_Up"),
    path("progresstable/", views.Progress_table, name="Progress_table"),
    path("template/", views.testing, name="testing"),
    path('addemployee/', views.Add_employee, name='Add_employee'),
    path('modifyemployee/', views.Modify_employee, name='Modify_employee'),
    path('applyleave/', views.Apply_leave, name='leave'),
    path('applyloan/', views.Apply_loan, name='loan'),
    path('getpayslip/',views.view_payslip, name='payslip'),
    path('download/',views.download_payslip,name='download_payslip'),
    path('downloadHR/',views.download_payslip_HR,name='downloadHR'),
    path("searchhr/", views.searchhr, name="SearchHR"),
    

        ] 

Payroll_Management_System/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Management.urls")),
    
]

Management/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class Employee(models.Model):
    EmpId = models.IntegerField(primary_key=True)
    EmpName = models.CharField(max_length=64)
    Role= models.CharField(max_length=20)
    Department= models.CharField(max_length=20)
    Username= models.CharField(max_length=30)
    Password= models.CharField(max_length=30)
    Manager_ID= models.IntegerField()
    Phone_No= models.CharField(max_length=10)
    Email_ID= models.CharField(max_length=30)
    IFSC_code= models.CharField(max_length=15)
    Door_No= models.IntegerField()
    Street= models.CharField(max_length=20)
    City= models.CharField(max_length=20)
    State= models.CharField(max_length=20)
    Country= models.CharField(max_length=20)
    Pin_code= models.IntegerField()
    DOB =  models.DateField()
    DOJ =  models.DateField()
    PAN_No= models.CharField(max_length=10)
    Acc_No=models.IntegerField()
    Loan_taken=models.BooleanField()
    Max_no_of_leaves=models.IntegerField()

    def __str__(self):
        return f"{self.EmpId}: {self.EmpName}"

class Progress(models.Model):
    EmpId = models.CharField(max_length=12)
    EffectiveDate =  models.DateField()
    Grade = models.CharField(max_length=64)
    Salary = models.FloatField()
    PFTax = models.FloatField()
    IncomeTax = models.FloatField()
    BasicPay = models.FloatField()
    HRA = models.FloatField()
    Conveyance = models.FloatField()
    Allowance = models.FloatField()

    def __str__(self):
        return f"{self.EmpId}:  with salary of {self.Salary}. in Grade:{self.Grade}  from:{self.EffectiveDate}"
    
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['EmpId', 'EffectiveDate'], name='unique_progress')
        ]

    
class Leave(models.Model):
    EmpId = models.CharField(max_length=12)
    LeaveFrom =  models.DateField()
    LeaveTo =  models.DateField()
    
    def __str__(self):
        return f"{self.EmpId}:  has taken leave from {self.LeaveFrom} to {self.LeaveTo}"
    
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['EmpId', 'LeaveFrom'], name='unique_leave')
        ]

    
class Loan(models.Model):
    EmpId = models.CharField(max_length=12)
    AvailDate = models.DateField(primary_key=True)
    TotalLoanAmount = models.FloatField(null=False)
    Tenor = models.IntegerField(null=False)
    AmountPaid = models.FloatField(null=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['EmpId', 'AvailDate'], name='unique_loan')
        ]


class PayHistory(models.Model):
    EmpId = models.CharField(max_length=12)
    #month_year = models.DateField()
    PFTax = models.FloatField()
    IncomeTax = models.FloatField()
    BasicPay = models.FloatField()
    HRA = models.FloatField()
    Conveyance = models.FloatField()
    Allowance = models.FloatField()
    LossOfPay = models.FloatField()
    LoanDeduction = models.FloatField()
    FinalSalary = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        unique_together = ('EmpId', 'created_at')

   

    # def save(self, *args, **kwargs):
    #     #if not self.id:
    #     #    self.month_year = self.created_at.replace(day=1)
    #     super().save(*args, **kwargs)

Management/forms.py
from django import forms
from django.utils.translation import gettext as _


class LoginForm(forms.Form):
    Username = forms.CharField(
        widget= forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    Password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )

Management/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django import forms
from django.urls import reverse
from .models import Employee,Loan,Leave,Progress,PayHistory
from .models import Progress, Leave
from django.template import loader
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.hashers import check_password
from Management.models import Employee
from .forms import LoginForm
from django.contrib.auth import authenticate, login
from django import forms
from datetime import datetime
from django.utils.safestring import mark_safe
import openpyxl
from django.core import serializers
from decimal import Decimal
import json
from datetime import datetime

#Adding Favorite List
favorites = []

#Adding Complaint List
complaint_author = []
complaint_email = []
complaint_type = []
complaint_subject = []
complaint_message = []

class NewFavForm(forms.Form):
    new_favorite = forms.CharField(label="New Favorite", required="True")

class NewComplaintForm(forms.Form):
    name = forms.CharField(label="Your name:", max_length=100, required="True")
    sender = forms.EmailField(label="Your Email:", required="True")
    c_type = forms.CharField(label="Complaint Type:", required="True")
    subject = forms.CharField(label="Subject:", min_length=10, required="True")
    message = forms.CharField(label="Message:", max_length=300, required="True")

class NewSearchForm(forms.Form):
    query = forms.CharField(label="Employee ID:", max_length=100, required="True")

class NewSignupForm(forms.Form):
    Name = forms.CharField(label="Your Name:",max_length=64)
    Email = forms.EmailField(label="Your Email:",max_length=64)
    Password = forms.CharField(label="Password",max_length=64)
    Position = forms.CharField(label="Your Position",max_length=64)
    Salary = forms.IntegerField(label="Your Salary:")


#PROGRESS TABLE 
class Progresstable(forms.Form):
    EmpId = forms.CharField(label="Employee ID",max_length=12)
    EffectiveDate =  forms.DateField(label="Effective Date")
    Grade = forms.CharField(label="Grade",max_length=64)
    PFTax = forms.FloatField(label="PF Tax ")
    IncomeTax = forms.FloatField(label="Income Tax")
    BasicPay = forms.FloatField(label="Basic Pay")
    HRA = forms.FloatField(label="HR allowance")
    Conveyance = forms.FloatField(label="Conveyance")
    Allowance = forms.FloatField(label="Allowance")

class AddEmployee(forms.Form):
    EmpId = forms.IntegerField(label=mark_safe("<br />Employee_ID"))
    EmpName = forms.CharField(label=mark_safe("<br />Employee Name"),max_length=30)
    Role= forms.CharField(label=mark_safe("<br />Role"),max_length=20)
    Department= forms.CharField(label=mark_safe("<br />Department"),max_length=20)
    Username= forms.CharField(label=mark_safe("<br />Username"),max_length=30)
    Password= forms.CharField(label=mark_safe("<br />Password"),max_length=30)
    Manager_ID= forms.IntegerField(label=mark_safe("<br />Manager ID"))
    Phone_No= forms.CharField(label=mark_safe("<br />Phone number"),max_length=10)
    Email_ID= forms.CharField(label=mark_safe("<br />Email ID"),max_length=30)
    IFSC_code= forms.CharField(label=mark_safe("<br />IFSC Code"),max_length=15)
    Door_No= forms.IntegerField(label=mark_safe("<br />Door number"))
    Street= forms.CharField(label=mark_safe("<br />Street"),max_length=20)
    City= forms.CharField(label=mark_safe("<br />City"),max_length=20)
    State= forms.CharField(label=mark_safe("<br />State"),max_length=20)
    Country= forms.CharField(label=mark_safe("<br />Country"),max_length=20)
    Pin_code= forms.IntegerField(label=mark_safe("<br />Pincode"))
    DOB =  forms.DateField(label=mark_safe("<br />Date of birth "))
    DOJ =  forms.DateField(label=mark_safe("<br />Date of joining"))
    PAN_No=forms.CharField(label=mark_safe("<br />Pancard Number"),max_length=10)
    Acc_No=forms.IntegerField(label=mark_safe("<br />Account number"))
    Loan_taken=forms.BooleanField(label=mark_safe("<br />Loan taken<br />"), required=False)
    Max_no_of_leaves=forms.IntegerField(label=mark_safe("<br />Max no of leaves "))

class ModifyEmployee(forms.Form):
    EmpId = forms.IntegerField(label="Employee_ID")
    EmpName = forms.CharField(label="Employee_Name",max_length=64)
    Role= forms.CharField(label="Role",max_length=20)
    Department= forms.CharField(label="Department",max_length=20)
    Username= forms.CharField(label="Username",max_length=30)
    Password= forms.CharField(label="Password",max_length=30)
    Manager_ID= forms.IntegerField(label="Manager_ID")
    Phone_No= forms.CharField(label="Phone_number",max_length=10)
    Email_ID= forms.CharField(label="Email_ID",max_length=30)
    IFSC_code= forms.CharField(label="IFSC_code",max_length=15)
    Door_No= forms.IntegerField(label="Door_number")
    Street= forms.CharField(label="Street",max_length=20)
    City= forms.CharField(label="City",max_length=20)
    State= forms.CharField(label="State",max_length=20)
    Country= forms.CharField(label="Country",max_length=20)
    Pin_code= forms.IntegerField(label="Pin_code")
    DOB =  forms.DateField(label="Date_of_birth")
    DOJ =  forms.DateField(label="Date_of_joining")
    PAN_No=forms.CharField(label="Pancard_number",max_length=10)
    Acc_No=forms.IntegerField(label="Account_number",)
    Loan_taken=forms.BooleanField(label="Loan_taken")
    Max_no_of_leaves=forms.IntegerField(label="Maximum_number_of_leaves")


# class AddEmployee(forms.Form):
#     EmpId = forms.IntegerField(label="Employee_ID")
#     EmpName = forms.CharField(label="Employee_Name",max_length=64)
    # Role= forms.CharField(label="Role",max_length=20)
    # Department= forms.CharField(label="Department",max_length=20)
    # Username= forms.CharField(label="Username",max_length=30)
    # Password= forms.CharField(label="Password",max_length=30)
    # Manager_ID= forms.IntegerField(label="Manager_ID")
    # Phone_No= forms.CharField(label="Phone_number",max_length=10)
    # Email_ID= forms.CharField(label="Email_ID",max_length=30)
    # IFSC_code= forms.CharField(label="IFSC_code",max_length=15)
    # Door_No= forms.IntegerField(label="Door_number")
    # Street= forms.CharField(label="Street",max_length=20)
    # City= forms.CharField(label="City",max_length=20)
    # State= forms.CharField(label="State",max_length=20)
    # Country= forms.CharField(label="Country",max_length=20)
    # Pin_code= forms.IntegerField(label="Pin_code")
    # DOB =  forms.DateField(label="Date_of_birth")
    # DOJ =  forms.DateField(label="Date_of_joining")
    # PAN_No=forms.CharField(label="Pancard_number",max_length=10)
    # Acc_No=forms.IntegerField(label="Account_number",)
    # Loan_taken=forms.BooleanField(label="Loan_taken")
    # Max_no_of_leaves=forms.IntegerField(label="Maximum_number_of_leaves")

# def Add_employee(request):
#     if request.method == "POST":
#         form = AddEmployee(request.POST)
#         if form.is_valid():
#             empID = form.cleaned_data['EmpId']
#             empName = form.cleaned_data['EmpName']
#             # role= form.cleaned_data['Role']
#             # department= form.cleaned_data['Department']
#             # username= form.cleaned_data['Username']
#             # password= form.cleaned_data['Password']
#             # manager_ID= form.cleaned_data['Manager_ID']
#             # phone_No= form.cleaned_data['Phone_No']
#             # email_ID= form.cleaned_data['Email_ID']
#             # iFSC_code= form.cleaned_data['IFSC_code']
#             # door_No= form.cleaned_data['Door_No']
#             # street= form.cleaned_data['Street']
#             # city= form.cleaned_data['City']
#             # state= form.cleaned_data['State']
#             # country= form.cleaned_data['Country']
#             # pin_code= form.cleaned_data['Pin_code']
#             # dOB =  form.cleaned_data['DOB']
#             # dOJ =  form.cleaned_data['DOJ']
#             # pAN_No=form.cleaned_data['PAN_No']
#             # acc_No=form.cleaned_data['Acc_No']
#             # loan_taken=form.cleaned_data['Loan_taken']
#             # max_no_of_leaves=form.cleaned_data['Max_no_of_leaves']
#             # add_employee = Employee(EmpId=empID,EmpName= empName, Role= role, Department= department, Username= username, Password=password, Manager_ID=manager_ID, Phone_No=phone_No, Email_ID=email_ID, IFSC_code=iFSC_code, Door_No=door_No, Street=street, City=city, State=state, Country=country, Pin_code=pin_code, DOB=dOB, DOJ=dOJ, PAN_No=pAN_No, Acc_No=acc_No, Loan_taken=loan_taken, Max_no_of_leaves=max_no_of_leaves )
#             add_employee = Employee(EmpId = empID,EmpName = empName)
#             add_employee.save()
#             return HttpResponseRedirect(reverse("Management:Add_employee"))
#         else:
#             return render(request, "Management/Add_employee.html", {
#                 "form": form,
#             })
    
#     return render(request, "Management/Add_employee.html", {
#         "form": AddEmployee(),
#     })

#------------------------------------------------------------------------------------------------

class Applyleave(forms.Form):
    EmpId = forms.IntegerField(label="Employee ID")
    LeaveFrom=forms.DateField(label = "Leave From  Date")
    LeaveTo=forms.DateField(label="Leave To Date")

class Applyloan(forms.Form):
    EmpId = forms.IntegerField(label="Employee ID")
    AvailDate=forms.DateField(label= "Date")
    TotalLoanAmount = forms.FloatField(label = "Loan amount ")
    Tenor = forms.IntegerField(label = "Tenor")    

class Getpayslip(forms.Form):
    EmpId = forms.IntegerField(label="Employee ID")
    month = forms.IntegerField(label="Month")
    year =  forms.IntegerField(label="Year")

# Create your views here.
def indexEMP(request):
    return render(request, "Management/indexEMP.html", {
        "favorites": favorites
    })

def index(request):
    return render(request, "Management/index.html", {

Management/templates/Management/add_favourite.html
{% extends "Management/layout.html" %}

{% block title %} Add Favourites {% endblock title %}

{% block body %}
    <h1>Add Favorites</h1>
    <form action="{% url 'Management:Add_Favourite' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <div class="container">
        <a href="{% url 'Management:View_Favourite' %}">View Tasks</a>
    </div>
{% endblock %}

Management/templates/Management/addemployee.html
{% extends "Management/layout.html" %}
{% load crispy_forms_tags %}

{% block title %} Progresstable {% endblock title %}

{% block body %}
    <div>
    <form action="{% url 'Management:Add_employee' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit">
    </form>
    </div>
{% endblock %}

Management/templates/Management/applyleave.html
{% extends "Management/layout.html" %}

{% block title %} Progresstable {% endblock title %}

{% block body %}
    <h2>Apply leave</h2>
    <form action="{% url 'Management:leave' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>

{% endblock %}

Management/templates/Management/displaypayslip.html
{% extends "Management/layout.html" %}
{% block title %} Progresstable {% endblock title %}
{% block body %}
    <table id="code" style="position: relative; margin-right: 30px; padding: 15px;border-spacing:30px;">
        <tr>
            <td>ID</td>
            <td>{{ payhistory.EmpId }}</td>
        </tr>
        <tr>
            <td>PFTax</td>
            <td>{{ payhistory.PFTax }}</td>
        </tr>
        <tr>
            <td>IncomeTax</td>
            <td>{{ payhistory.IncomeTax }}</td>
        </tr>
        <tr>
            <td>BasicPay</td>
            <td>{{ payhistory.BasicPay }}</td>
        </tr>
        <tr>
            <td>HRA</td>
            <td>{{ payhistory.HRA }}</td>
        </tr>
        <tr>
            <td>Conveyance</td>
            <td>{{ payhistory.Conveyance }}</td>
        </tr>
        <tr>
            <td>Allowance</td>
            <td>{{ payhistory.Allowance }}</td>
        </tr>
        <tr>
            <td>Loss of Pay</td>
            <td>{{ payhistory.LossOfPay }}</td>
        </tr>
        <tr>
            <td>LoanDeduction</td>
            <td>{{ payhistory.LoanDeduction }}</td>
        </tr>
        <tr>
            <td>FinalSalary</td>
            <td>{{ payhistory.FinalSalary }}</td>
        </tr>
        
    </table>
    <br><br>
    <p>
        <center><a href="{% url 'Management:download_payslip' %}">Download Payslip</a></center>
    </p>
{% endblock %}

Management/templates/Management/favourite.html
{% extends "Management/layout.html" %}

{% block title %} View Favourite {% endblock title %}

{% block body %}
<h1>Favorites</h1>
<div class="skills">
    <ul>
        {% for fav in favorites %}
            <span>{{ fav }}</span>
            {% empty %}
            <p>No Such Favorites</p>
        {% endfor %}
    </ul>
</div>
    <a href="{% url 'Management:Add_Favourite' %}">Add a New Favourite</a>
{% endblock body %}

Management/templates/Management/getpayslip.html
{% extends "Management/layout.html" %} {% block title %} Progresstable {% endblock title %} {% block body %}
<h2>Get payslip</h2>
<form action="{% url 'Management:payslip' %}" method="POST">
    {% csrf_token %} {{ form }}
    <input type="submit">
</form>

{% endblock %}

Management/templates/Management/index.html
{% extends "Management/layout.html" %}

{% block title %} Home Page {% endblock title %}

{% block body %}

<a href="{% url 'Management:SearchHR' %}" class="repoCard" rel="noopener noreferrer">
   <div class="repoTitle">Search</div>
   <p>Search Employee With their ID </p>
</a>
<a href="{% url 'Management:Add_employee' %}" class="repoCard" rel="noopener noreferrer">
   <div class="repoTitle">Add Employee</div>
   <p>Add new employee </p>
</a>
<a href="{% url 'Management:update' %}" class="repoCard" rel="noopener noreferrer">
   <div class="repoTitle">Monthly update</div>
   <p>Calculates monthly salary for every employees</p>
</a>
<a href="{% url 'Management:Progress_table' %}" class="repoCard" rel="noopener noreferrer">
   <div class="repoTitle">Progress</div>
   <p>Update change in salary structure</p>
</a>
<a href="{% url 'Management:Modify_employee' %}" class="repoCard" rel="noopener noreferrer">
   <div class="repoTitle">Modify Employee</div>
   <p>Modify employee tables </p>
</a>
<a href="{% url 'Management:downloadHR' %}" class="repoCard" rel="noopener noreferrer">
   <div class="repoTitle">Get salary excel </div>
   <p>Download current month Employees salary details </p>
</a>
{% endblock body%}

Management/templates/Management/indexEMP.html
{% extends "Management/layout.html" %}

{% block title %} Home Page {% endblock title %}

{% block body %}
<a href="{% url 'Management:searchEMP' %}" class="repoCard" rel="noopener noreferrer">
   <div class="repoTitle">Search</div>
   <p>Search employee with their ID</p>
</a>
<a href="{% url 'Management:leave' %}" class="repoCard" rel="noopener noreferrer">
   <div class="repoTitle">Apply leave</div>
   <p>Employees can apply leave</p>
</a>
<a href="{% url 'Management:loan' %}" class="repoCard" rel="noopener noreferrer">
   <div class="repoTitle">Apply Loan</div>
   <p>Employees can apply for loan</p>
</a>
<a href="{% url 'Management:payslip' %}" class="repoCard" rel="noopener noreferrer">
   <div class="repoTitle">Payslip</div>
   <p>Employees can view their Payslip</p>
</a>
{% endblock body%}

Management/templates/Management/login.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>Login</title>
  </head>
  <body>
  <div class="content">
    <div class="container">
      <div class="row justify-content-center">
        <!-- <div class="col-md-6 order-md-2">
          <img src="images/undraw_file_sync_ot38.svg" alt="Image" class="img-fluid">
        </div> -->
        <div class="col-md-6 contents">
          <div class="row justify-content-center">
            <div class="col-md-12">
              <div class="form-block">
                  <div class="mb-4">
                </div>

              <span class="mb-0 text-muted">
                {% if msg %}
                    {{ msg | safe }}
                {% else %}
                    Login page
                {% endif %}
              </span>
                <form  method="post">
                    {% csrf_token %}
                  <div class="form-group first">
                    <label for="Username">Username</label>
                      {{ form.Username }}
                  </div>
                  <div class="form-group last mb-4">
                    <label for="Password">Password</label>
                    {{ form.Password }}
                  </div>

                  <!-- <div class="d-flex mb-5 align-items-center">
                    <label class="control control--checkbox mb-0"><span class="caption">Remember me</span>
                      <input type="checkbox" checked="checked"/>
                      <div class="control__indicator"></div>
                    </label>
                    <span class="ml-auto"><a href="#" class="forgot-pass">Forgot Password</a></span>
                  </div> -->

                  <input type="submit" value="Log In" class="btn btn-pill text-white btn-block btn-primary">
                </form>
              </div>
            </div>
          </div>

        </div>

      </div>
    </div>
  </div>


    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

Management/templates/Management/modifyemployee.html
{% extends "Management/layout.html" %}



{% block body %}
    <h2>Modify employee table</h2>
    <form action="{% url 'Management:Modify_employee' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
{% endblock %}

Management/templates/Management/progresstable.html
{% extends "Management/layout.html" %}



{% block body %}
    <form action="{% url 'Management:Progress_table' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>

    
{% endblock %}

Management/templates/Management/register.html
<html>
<head>
    <style>
        form {
            max-width: 1000px; 
            margin: 20px auto;
            border: 2px solid #ccc;
            background-color: #f8f8f8;
            padding: 10px;
            font-family: "Helvetica Neue", Arial, sans-serif;
        }
        
        .form-control {
            border-radius: 0;
            border: 2px solid #ccc;
        }
        
        form > * {
            margin-bottom: 15px;
        }
        

        label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
            color: #333;
        }
        
        
        input[type="checkbox"], input[type="radio"] {
            margin-right: 5px;
        }
        
        button[type="submit"] {
            display: inline-block;
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 4px;
            text-transform: uppercase;
            font-weight: bold;
            letter-spacing: 1px;
            cursor: pointer;
        }
        
        button[type="submit"]:hover {
            background-color: #0069d9;
        }        
          
    </style>
</head>


{% load crispy_forms_tags %}
{% block content %}


<form action="{% url 'Management:register' %}" method="POST">
{% csrf_token %}
{{ form.as_p}}
<button type="submit" class= "btn btn-primary">Submit</button>
</form>
{% endblock %}
<html>

Management/templates/Management/searchhr.html
{% extends "Management/layout.html" %} {% block title %} Search {% endblock title %} {% block body %} {% if method == "GET" %}
<h1>Search an Employee</h1>
{% else %}
<h1>Results</h1>
{% endif %}
<form action="{% url 'Management:SearchHR' %}" method="POST">
    {% csrf_token %} {{ form }}
    <input type="submit">
</form>
</div>
<div class="repoContainer">
    {% if not result and method == "POST" %}
    <p>No Result Found</p>
    {% elif method == "GET" %}
    <p></p>
    {% else %}
    <table id="code" style="position: relative; margin-right: 30px; padding: 15px;border-spacing:30px;">
        {% for r in result %}
        <tr>
            <td>ID</td>
            <td>{{ r.EmpId }}</td>
        </tr>
        <tr>
            <td>BasicPay</td>
            <td>{{ r.BasicPay }}</td>
        </tr>
        <tr>
            <td>Allowance</td>
            <td>{{ r.Allowance }}</td>
        </tr>
        

        {% empty %}
        <td colspan="5" style="text-align: center; color: aqua;">No Result</td>
        {% endfor %}
    </table>
    {% endif %}
{% endblock body%}